### ISSUE TITLE
Optimize the performance of the Newton solver

### ISSUE THREAD

**Issue by JunnanZ** [jstac/sdfs_via_autodiff#2]
The Newton solver already uses the more efficient `jax.jvp` function. We might be able to improve the part where it computes $J^{-1}$, but I tried two other solvers and both are much slower than the current one.

However, I found that jitting the inner function can make it much faster, that is,

```python
@jax.jit
def q(x):
```

This might have optimized memory use internally as well. With this, I'm able to make Newton's method slightly faster than successive evaluations and AA on a reasonably large grid.

@jstac, would mind trying if the above also works in the discrete case? (I don't see see the notebooks for the discrete case.)

**Comment by jstac** [comment]
> The Newton solver already uses the more efficient `jax.jvp` function. 

Oh yeah, I forgot I already worked on that :grimacing: 

> @jstac, would mind trying if the above also works in the discrete case? (I don't see see the notebooks for the discrete case.)

Yes, I also get a speed gain.  Well spotted. I've added that change in 

> With this, I'm able to make Newton's method slightly faster than successive evaluations and AA on a reasonably large grid.

Hmmm.  I feel like it should do better.   I think the issue is that differentiating through that particular approximation method is expensive.  (On the other hand, it's nice that it's stable.)

**Comment by JunnanZ** [comment]
> Hmmm. I feel like it should do better. I think the issue is that differentiating through that particular approximation method is expensive.

Yeah, and inverting the Jacobian can also be slow. 

I tried implementing kernel averaging. The main problem is memory use. In my implementation, I use `jax.vmap` to vectorize the computation, but it will generate very large intermediate arrays. (Usually, `jax.jit` will take care of intermediate arrays and optimize memory use, but it doesn't work this time.) This problem is much more severe for kernel averaging, since we need to use all function values stored on the grid. (I guess we can restrict to adjacent data points.) Currently, my kernel averaging code is faster than my previous linear approximation for a single point, but it runs out of memory very quickly when I increase the number of points to approximate. I'm still investigating this.

I feel like Jax is inferior to Numba in this case. For Jax, we write vectorized code, but it easily uses up all GPU memory, and there is no way to write efficient loops that can be run in parallel. For small scale computation, Jax can be really fast, but when the state space is large for example, how to allocate memory is a big problem. I haven't found a good way to deal with this issue.

**Comment by jstac** [comment]
Thanks for the report @JunnanZ .  

I wonder if `jax.vmap` is the problem here.  It might not be as efficient as a totally vectorized solution.

**Comment by jstac** [comment]
I think you are right that kernel averaging will be very memory intensive and it's probably not suitable after all, @JunnanZ .  Thanks for investigating it.

I think `jax.vmap` might be an issue, regardless.  If we partially vectorize and then do the rest with `jax.vmap`, the compiler sees the problem in pieces rather than as a whole.  This makes it hard to optimize and parallelize efficiently.

I've actually been very impressed with memory management in JAX for the discrete case, since the state space is of size n and hence matrices that act on these vectors, such as the $H$ in $Tw = 1 + (H w^\theta)^(1/\theta)$, never need to be instatiated.  We can just write them as linear operators.  So I don't have anything in memory bigger than $n$.  This is fine, since only $n \times n$ is a problem.

**Comment by JunnanZ** [comment]
Hi @jstac,

> I think jax.vmap might be an issue, regardless. If we partially vectorize and then do the rest with jax.vmap, the compiler sees the problem in pieces rather than as a whole. This makes it hard to optimize and parallelize efficiently.

Inspired by your discrete code, I also tried vectorizing my computation for the continuous case (using broadcasting) and avoiding `jax.vmap`. However, the performance is pretty much the same as my code using `jax.vmap`, for all 3 algorithms. (so Newton's method still only outperforms the other two by a little) This is a bit surprising. I thought there would be at least some differences in performance.

Maybe the linear approximation method `map_coordinates` makes `jax.jvp` slow.

**Comment by jstac** [comment]
Thanks @JunnanZ , I'm glad you investigated that.

> Maybe the linear approximation method map_coordinates makes jax.jvp slow.

I can't think of any other explanation...

**Comment by JunnanZ** [comment]
Hi @jstac, it seems that my previous results were not quite right. I chose a grid that was too "sparse" (large standard deviations when building the grid) to store the function, which might have led to WC ratios that were too small. In this setting, all algorithms converge pretty quickly.

Now I switch to a denser grid, the computed WC ratios are closer to the log-linear approximations. Interestingly, the other 2 algorithms slow down quite a bit but Newton's method is still very fast. On a grid of 15^4, successive approximation takes 160s, AA takes 80s, and Newton's method takes only 10s on my machine.

It seems that the choice of grid has a big influence on the final results, which needs to be investigated. But I'm glad that Newton's method also works very well in the continuous case.

**Comment by jstac** [comment]
That's great @JunnanZ , nice work.

> On a grid of 15^4

So that doesn't lead to a memory error, unlike the discrete case?  (In the discrete case one of the states is double indexed due to stochastic volatility, so it's memory requirement might be larger.)

**Comment by JunnanZ** [comment]
> So that doesn't lead to a memory error, unlike the discrete case?

No, it doesn't. I think it's because I only use 5 quadrature nodes in each dimension (using 6 would fail), while in the discrete case, it probably needs more than that to evaluate the expectation.

**Comment by jstac** [comment]
OK to close @JunnanZ ?
