### ISSUE TITLE
shift continuous state vectorized to a branch

### ISSUE THREAD

**Issue by jstac** [jstac/sdfs_via_autodiff#8]
Shift to a branch if not being used: https://github.com/jstac/sdfs_via_autodiff/blob/main/code/ssy/continuous_junnan/ssy_wc_ratio_continuous_vectorized.py

CC @JunnanZ

**Comment by JunnanZ** [comment]
Code moved to https://github.com/jstac/sdfs_via_autodiff/tree/ssy_continuous_vectorized
